dataset:
  train_data:
    root: E:\dataset\PennFudanPed
    annFile: E:\dataset\PennFudanPed\annotations\PennFudanPed.json
  val_data:
    root: E:\dataset\PennFudanPed
    annFile: E:\dataset\PennFudanPed\annotations\PennFudanPed.json
  test_data:
    root: E:\dataset\PennFudanPed
    annFile: E:\dataset\PennFudanPed\annotations\PennFudanPed.json
  resize: [800, 800]
  max_objs_per_image: 10
  batch_size: 1
  num_works: 2

model:
  name: faster_rcnn_resnet34
  backbone_pertrained: False
  load_from: ~  # 使用~表示null

train:
  log: work_dir/log
  checkpoint: work_dir/checkpoint
  epochs: 12
  lr: 0.001
  gpus: ~
  resume_from: ~

debug: False