dataset:
  train_data:
    root: /root/userfolder/datasets/PennFudanPed
    annFile: /root/userfolder/datasets/PennFudanPed/annotations/PennFudanPed.json
  val_data:
    root: /root/userfolder/datasets/PennFudanPed
    annFile: /root/userfolder/datasets/PennFudanPed/annotations/PennFudanPed.json
  test_data:
    root: /root/userfolder/datasets/PennFudanPed
    annFile: /root/userfolder/datasets/PennFudanPed/annotations/PennFudanPed.json
  resize: [800, 800]
  max_objs_per_image: 10
  batch_size: 2   # batch size per device
  num_works: 4

model:
  name: faster_rcnn_resnet50_fpn
  backbone_pertrained: true
  obj_thresh: 0.4
  load_from: ~

train:
  log: work_dir/log
  checkpoint: work_dir/checkpoint
  result: work_dir/result
  multi_process: True
  log_every_step: 10
  epochs: 12
  lr: 0.05
  gpus: [0, 1, 2]
  resume_from: ~

debug: False